// <auto-generated />
using System;
using Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.SharedKernel.Common.ApiRequestBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Requests", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApiRequestBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.SharedKernel.Common.ApiResponseBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Responses", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApiResponseBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.SharedKernel.Requests.CreateCuentaRequest", b =>
                {
                    b.HasBaseType("Api.SharedKernel.Common.ApiRequestBase");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.HasDiscriminator().HasValue("CreateCuentaRequest");
                });

            modelBuilder.Entity("Api.SharedKernel.Requests.CreatePolizaRequest", b =>
                {
                    b.HasBaseType("Api.SharedKernel.Common.ApiRequestBase");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CreatePolizaRequest");
                });

            modelBuilder.Entity("Api.SharedKernel.Requests.CreateCuentaResponse", b =>
                {
                    b.HasBaseType("Api.SharedKernel.Common.ApiResponseBase");

                    b.Property<string>("Model")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.HasDiscriminator().HasValue("CreateCuentaResponse");
                });

            modelBuilder.Entity("Api.SharedKernel.Requests.CreatePolizaResponse", b =>
                {
                    b.HasBaseType("Api.SharedKernel.Common.ApiResponseBase");

                    b.Property<string>("Model")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.HasDiscriminator().HasValue("CreatePolizaResponse");
                });

            modelBuilder.Entity("Api.SharedKernel.Common.ApiResponseBase", b =>
                {
                    b.HasOne("Api.SharedKernel.Common.ApiRequestBase", null)
                        .WithOne("Response")
                        .HasForeignKey("Api.SharedKernel.Common.ApiResponseBase", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.SharedKernel.Common.ApiRequestBase", b =>
                {
                    b.Navigation("Response");
                });
#pragma warning restore 612, 618
        }
    }
}
